export const HPAtoZAnatomyMap = {
  "adrenal gland": "AdrenalGland",
  "appendix": "Appendix",
  "bone marrow": "BoneMarrow",
  "breast": "Breast",
  "bronchus": "Bronchus",
  "caudate": "Caudate",
  "cerebellum": "Cerebellum",
  "cerebral cortex": "CerebralCortex",
  "cervix, uterine": "CervixUterine",
  "colon": "Colon",
  "duodenum": "Duodenum",
  "endometrium 1": "Endometrium1",
  "endometrium 2": "Endometrium2",
  "epididymis": "Epididymis",
  "esophagus": "Esophagus",
  "fallopian tube": "FallopianTube",
  "gallbladder": "Gallbladder",
  "heart muscle": "Heart",
  "hippocampus": "Hippocampus",
  "kidney": "Kidney",
  "liver": "Liver",
  "lung": "Lung",
  "lymph node": "LymphNode",
  "nasopharynx": "Nasopharynx",
  "oral mucosa": "OralMucosa",
  "ovary": "Ovary",
  "pancreas": "Pancreas",
  "parathyroid gland": "ParathyroidGland",
  "placenta": "Placenta",
  "prostate": "Prostate",
  "rectum": "Rectum",
  "salivary gland": "SalivaryGland",
  "seminal vesicle": "SeminalVesicle",
  "skeletal muscle": "SkeletalMuscle",
  "skin 1": "Skin",
  "skin 2": "Skin",
  "small intestine": "SmallIntestine",
  "smooth muscle": "SmoothMuscle",
  "soft tissue 1": "SoftTissue",
  "soft tissue 2": "SoftTissue",
  "spleen": "Spleen",
  "stomach 1": "Stomach",
  "stomach 2": "Stomach",
  "testis": "Testis",
  "thyroid gland": "ThyroidGland",
  "tonsil": "Tonsil",
  "urinary bladder": "UrinaryBladder",
  "vagina": "Vagina",
  "retina": "Retina",
  "lactating breast": "Breast",
  "pituitary gland": "PituitaryGland"
};
