#Deployment / produktion (Azure)

# [infra-repo]           ← separat repo för infrastruktur
# │
# ├─ azure-mongo.yaml     ← beskriver MongoDB-instans i Azure
# ├─ azure-backend.yaml   ← beskriver backend-container i Azure (t.ex. ACI eller Kubernetes)
# └─ pipelines/           ← CI/CD-skript som deployar backend och databasen AUTOMATISERAT(kolla nere), annars manuelt(kolla nere)
                            

#infra-repo/
#├─ myproject1/
#│  ├─ azure-mongo.yaml
#│  ├─ azure-backend.yaml
#├─ myproject2/
#│  ├─ azure-mongo.yaml
#│  └─ azure-backend.yaml
#└─ shared/       ← resurser som används av flera projekt




name: mongo-service
type: containerapp
location: westeurope
#NOTE# Bra att här nonstans anges DB namn och kollektioner som "resources" !!!
properties:
  environmentId: /subscriptions/<SUB_ID>/resourceGroups/<RG>/providers/Microsoft.Web/containerApps/<ENV>
  configuration:
    ingress:
      external: true
      targetPort: 27017
    secrets: []
    volumes:
      - name: mongodata
        storageType: azureFile
        path: /data/db
  template:
    containers:
      - name: mongo
        image: mongo:latest
        volumeMounts:
          - volumeName: mongodata
            mountPath: /data/db
    scale:
      minReplicas: 1
      maxReplicas: 3
      rules:
        - name: cpu-scale
          custom:
            type: cpu
            metadata:
              threshold: "80"

#-------------------------------hur kör man den manuellt---------------------------------------

#1. Via terminal / CLI

#Öppna terminalen lokalt på din dator (eller i VS Code).

#Du måste ha Azure CLI installerad och vara inloggad:

#az login


#Kör sedan YAML-filen för att skapa resurser i en specifik resource group:

#az deployment group create \
#  --resource-group myResourceGroup \
#  --template-file azure-mongo.yaml


#Detta skapar MongoDB i Azure enligt definitionen i YAML-filen.

#Allt sker via kommandon – VS Code används bara som editor om du vill läsa/ändra filen.

#2. Via VS Code med Azure Extension

#Installera t.ex. Azure Resource Manager Tools extension i VS Code.

#Öppna YAML-filen i VS Code → du får syntax-highlighting och validiering.

#Du kan högerklicka → “Deploy to Azure” (eller liknande)

#Under huven körs samma CLI-kommandon (az deployment group create)

#Du loggar in via extensionen och väljer resource group




#-------------------------------hur kör man den automatiserat---------------------------------------


infra-repo/                      ← Ditt separata repo för infrastruktur
│
├── azure-mongo.yaml             ← Azure-resursfil (infrastruktur)
│
└── .github/                   ← pipeline
    └── workflows/
        └── deploy-infra.yaml  


#   !!!!   Varje gång du gör git push till main i infra-repo,---------------------------------------------
#    !!!   så startar GitHub Actions pipelinen.-----------------------------------------------

#  deploy-infra.yaml
name: Deploy Infra

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy MongoDB
        run: |
          az deployment group create \
            --resource-group $RESOURCE_GROUP \
            --template-file azure-mongo.yaml

